name: 🤖 Android Builds
on:
  workflow_call:

jobs:
  android:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        arch: [{arch: "x86_64", rust: "x86_64-linux-android"}, {arch: "arm64",rust: "aarch64-linux-android"}]
        precision: [single, double]
        features: [simd-stable, enhanced-determinism]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch.arch }}
          rust_target: ${{ matrix.arch.rust }}
          platform: android
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features }}

      - name: Upload ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/upload
        with:
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features }}
