name: 🍎 macOS Builds
on:
  workflow_call:
    

# Global Settings
env:
  SCONSFLAGS: verbose=yes warnings=extra werror=yes

jobs:
  macos:
    runs-on: "macos-latest"
    name: ${{ matrix.target }} ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        arch:  [{arch: "universal", rust: "--target=x86_64-apple-darwin"}]
        precision: [single, double]
        features: [simd-stable, enhanced-determinism]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
    
      - name: Build ${{ matrix.target }} ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          arch: ${{ matrix.arch.arch }}
          rust_target: ${{ matrix.arch.rust }}
          platform: macos
          target: ${{ matrix.target }}
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features }}
      
      - name: Sign frameworks ${{ matrix.target }} ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        shell: pwsh
        env:
          APPLE_CERT_BASE64: ${{ secrets.PROD_MACOS_CERTIFICATE }}
          APPLE_CERT_PASSWORD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
          APPLE_DEV_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
          APPLE_DEV_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
          APPLE_DEV_PASSWORD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
          APPLE_DEV_APP_ID: ${{ secrets.PROD_MACOS_APPLE_DEV_APP_ID }}
        run: ./scripts/ci-sign-macos.ps1 bin/addons/godot-rapier2d/bin/libphysics_server_rapier2d.macos.${{ matrix.target }}.framework
        if: ${{ env.APPLE_DEV_ID }}

      - name: Upload ${{ matrix.target }} ${{ matrix.arch.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/upload
        with:
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features }}
